# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster
WORKDIR /code

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .

CMD [ "gunicorn", "-w" , "1", "-b", "0.0.0.0:9000","wsgi:app"]