#test the comparison of two json files
import sys
sys.path.append('../../')
from myutils import myutils
import json

def test_comp_jsons(test_client):

    firstcomp='''
    {
    "crc_cohort7/context/case_identification/patient_pseudonym": "59499",
    "crc_cohort7/context/case_identification/participation_in_clinical_study": "FALSE",
    "crc_cohort7/patient_data/gender/biological_sex|value": "FEMALE",
    "crc_cohort7/patient_data/gender/biological_sex|code": "8532",
    "crc_cohort7/patient_data/gender/biological_sex|terminology": "omop_vocabulary",
    "crc_cohort7/patient_data/primary_diagnosis/date_of_diagnosis": "2000-03-01T00:00:00.00Z",
    "crc_cohort7/patient_data/primary_diagnosis/diagnosis_timing/primary_diagnosis:0/age_at_diagnosis": "P67Y",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis2/metastasis_diagnosis/time_of_recurrence": "P112W",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/anatomical_pathology_examination/anatomical_pathology_finding:0/media_file/availability_digital_imaging": "Can be generated",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/invasion_front/anatomical_pathology_finding/digital_imaging_invasion_front/availability_invasion_front_digital_imaging": "Can be generated",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/localization_of_primary_tumor|value": "C 20 - Rectum",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/localization_of_primary_tumor|code": "74582",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/localization_of_primary_tumor|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/morphology|value": "Adenocarcinoma",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/morphology|code": "42530737",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/morphology|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/primary_tumour|value": "T3",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/primary_tumour|code": "4234703",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/primary_tumour|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/regional_lymph_nodes|value": "N2",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/regional_lymph_nodes|code": "45881614",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/regional_lymph_nodes|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/distant_metastasis|value": "MX",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/distant_metastasis|code": "45876323",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/distant_metastasis|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/grade|value": "G3",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/grade|code": "36769033",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/grade|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/stage|value": "Stage - III",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/stage|code": "45878643",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/stage|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/uicc_version": "5th. ed (used 1998-2002)",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/histological_grading/who_version": "2nd ed. (1991- 2000)",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/distant_metastasis/anatomical_location:0/localization_of_metastasis|value": "Lymph Nodes",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/distant_metastasis/anatomical_location:0/localization_of_metastasis|code": "45881859",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/distant_metastasis/anatomical_location:0/localization_of_metastasis|terminology": "omop_vocabulary",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|id": "557",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|issuer": "unknown",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|assigner": "unknown",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|type": "unknown",
    "crc_cohort7/sample/biospecimen_summary:0/material_type|value": "Tumor tissue sample",
    "crc_cohort7/sample/biospecimen_summary:0/material_type|code": "4122248",
    "crc_cohort7/sample/biospecimen_summary:0/material_type|terminology": "omop_vocabulary",
    "crc_cohort7/sample/biospecimen_summary:0/preservation_mode|value": "FFPE",
    "crc_cohort7/sample/biospecimen_summary:0/preservation_mode|code": "37206850",
    "crc_cohort7/sample/biospecimen_summary:0/preservation_mode|terminology": "omop_vocabulary",
    "crc_cohort7/sample/biospecimen_summary:0/specimen/year_of_sample_collection": "2000-01-01T00:00:00.00Z",
    "crc_cohort7/surgery/surgery:0/surgery_type|value": "Anterior resection of rectum",
    "crc_cohort7/surgery/surgery:0/surgery_type|code": "4166855",
    "crc_cohort7/surgery/surgery:0/surgery_type|terminology": "omop_vocabulary",
    "crc_cohort7/surgery/surgery:0/location_of_the_tumor|value": "C 20 - Rectum",
    "crc_cohort7/surgery/surgery:0/location_of_the_tumor|code": "74582",
    "crc_cohort7/surgery/surgery:0/location_of_the_tumor|terminology": "omop_vocabulary",
    "crc_cohort7/surgery/surgery:0/surgery_timing/surgery/surgery_start_relative": "P2W",
    "crc_cohort7/surgery/surgery:0/surgery_radicality|value": "R0",
    "crc_cohort7/surgery/surgery:0/surgery_radicality|code": "4121182",
    "crc_cohort7/surgery/surgery:0/surgery_radicality|terminology": "omop_vocabulary",
    "crc_cohort7/diagnostic_examinations/colonoscopy/colonoscopy": "Not done",
    "crc_cohort7/diagnostic_examinations/ct/ct": "Done, data available",
    "crc_cohort7/diagnostic_examinations/liver_imaging/liver_imaging": "Done, data available",
    "crc_cohort7/diagnostic_examinations/lung_imaging/lung_imaging": "Done, data available",
    "crc_cohort7/diagnostic_examinations/mri/mri": "Unknown",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/any_event:0/braf_pic3ca_her2_mutation_status": "Not done",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/any_event:0/microsatellite_instability": "Not done",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/nras_exon_4_codons_117_or_146|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/nras_exon_4_codons_117_or_146|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/nras_exon_4_codons_117_or_146|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/nras_exon_3_codons_59_or_61|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/nras_exon_3_codons_59_or_61|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/nras_exon_3_codons_59_or_61|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/nras_exon_2_codons_12_or_13|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/nras_exon_2_codons_12_or_13|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/nras_exon_2_codons_12_or_13|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/kras_exon_4_codons_117_or_146|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/kras_exon_4_codons_117_or_146|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/kras_exon_4_codons_117_or_146|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/kras_exon_3_codons_59_or_61|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/kras_exon_3_codons_59_or_61|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/kras_exon_3_codons_59_or_61|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/kras_exon_2_codons_12_or_13|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/kras_exon_2_codons_12_or_13|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/kras_exon_2_codons_12_or_13|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/any_event:0/mismatch_repair_gene_expression": "Not done",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status": "death for unknown reasons",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status_timing/timestamp_of_last_update_of_vital_status": "2002-04-01",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status_timing/overall_survival_status/overall_survival_status": "P109W",
    "crc_cohort7/patient_data/gender/encoding|code": "UTF-8",
    "crc_cohort7/patient_data/gender/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/patient_data/gender/language|code": "en",
    "crc_cohort7/patient_data/gender/language|terminology": "ISO_639-1",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis2/metastasis_diagnosis/from_event": "Primary diagnosis",
    "crc_cohort7/patient_data/metastasis_diagnosis/encoding|code": "UTF-8",
    "crc_cohort7/patient_data/metastasis_diagnosis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/patient_data/metastasis_diagnosis/language|code": "en",
    "crc_cohort7/patient_data/metastasis_diagnosis/language|terminology": "ISO_639-1",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis|value": "Metastasis",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis|code": "36769180",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/encoding|code": "UTF-8",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/language|code": "en",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/language|terminology": "ISO_639-1",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/test_name": "Histopathology analysis",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/time": "2018-11-07T00:00:00.00Z",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/encoding|code": "UTF-8",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/language|code": "en",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/language|terminology": "ISO_639-1",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/problem_diagnosis_name|value": "Colorectal cancer",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/problem_diagnosis_name|code": "44803809",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/problem_diagnosis_name|terminology": "omop_vocabulary",
    "crc_cohort7/sample/biospecimen_summary:0/encoding|code": "UTF-8",
    "crc_cohort7/sample/biospecimen_summary:0/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/sample/biospecimen_summary:0/language|code": "en",
    "crc_cohort7/sample/biospecimen_summary:0/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/colonoscopy/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/colonoscopy/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/colonoscopy/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/colonoscopy/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/colonoscopy/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/colonoscopy/language|code": "en",
    "crc_cohort7/diagnostic_examinations/colonoscopy/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/colonoscopy/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/diagnostic_examinations/colonoscopy/procedure_name": "Colonoscopy",
    "crc_cohort7/diagnostic_examinations/ct/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/ct/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/ct/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/ct/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/ct/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/ct/language|code": "en",
    "crc_cohort7/diagnostic_examinations/ct/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/ct/procedure_name": "CT",
    "crc_cohort7/diagnostic_examinations/ct/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/diagnostic_examinations/liver_imaging/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/liver_imaging/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/liver_imaging/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/liver_imaging/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/liver_imaging/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/liver_imaging/language|code": "en",
    "crc_cohort7/diagnostic_examinations/liver_imaging/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/liver_imaging/procedure_name": "Liver imaging",
    "crc_cohort7/diagnostic_examinations/liver_imaging/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/diagnostic_examinations/lung_imaging/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/lung_imaging/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/lung_imaging/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/lung_imaging/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/lung_imaging/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/lung_imaging/language|code": "en",
    "crc_cohort7/diagnostic_examinations/lung_imaging/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/lung_imaging/procedure_name": "Lung imaging",
    "crc_cohort7/diagnostic_examinations/lung_imaging/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/diagnostic_examinations/mri/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/mri/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/mri/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/mri/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/mri/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/mri/language|code": "en",
    "crc_cohort7/diagnostic_examinations/mri/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/mri/procedure_name": "MRI",
    "crc_cohort7/diagnostic_examinations/mri/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/any_event:0/test_name": "BRAF, PIC3CA, HER2 mutation test",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/any_event:0/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/any_event:0/test_name": "Microsatellite instability test",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/any_event:0/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/test_name": "KRAS mutation test",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/variant_name": "NRAS exon 4 (codons 117 or 146)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/variant_name": "NRAS exon 3 (codons 59 or 61)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/variant_name": "NRAS exon 2 (codons 12 or 13)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/variant_name": "KRAS exon 4 (codons 117 or 146)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/variant_name": "KRAS exon 3 (codons 59 or 61)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/variant_name": "KRAS exon 2 (codons 12 or 13)",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/any_event:0/test_name": "Mismatch repair gene expression",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/any_event:0/time": "9999-12-10T00:00:00.00Z",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/encoding|code": "UTF-8",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/language|code": "en",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/language|terminology": "ISO_639-1",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status_timing/overall_survival_status/from_event": "First colon cancer therapy",
    "crc_cohort7/surgery/surgery:0/ism_transition/current_state|value": "completed",
    "crc_cohort7/surgery/surgery:0/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/surgery/surgery:0/ism_transition/current_state|code": "532",
    "crc_cohort7/surgery/surgery:0/surgery_timing/surgery/from_event": "Primary diagnosis",
    "crc_cohort7/surgery/surgery:0/encoding|code": "UTF-8",
    "crc_cohort7/surgery/surgery:0/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/surgery/surgery:0/language|code": "en",
    "crc_cohort7/surgery/surgery:0/language|terminology": "ISO_639-1",
    "crc_cohort7/surgery/surgery:0/time": "2018-11-07T00:00:00.00Z",
    "crc_cohort7/language|code": "en",
    "crc_cohort7/language|terminology": "ISO_639-1",
    "crc_cohort7/context/start_time": "2022-03-15T12:04:38.49Z",
    "crc_cohort7/context/setting|code": "238",
    "crc_cohort7/context/setting|terminology": "openehr",
    "crc_cohort7/context/setting|value": "other care",
    "crc_cohort7/category|code": "433",
    "crc_cohort7/category|value": "event",
    "crc_cohort7/category|terminology": "openehr",
    "crc_cohort7/territory|code": "ZW",
    "crc_cohort7/territory|terminology": "ISO_3166-1",
    "crc_cohort7/composer|name": "EOSC-Life_WP1-DEM",
    "crc_cohort7/patient_data/primary_diagnosis/primary_diagnosis|value": "Colorectal cancer",
    "crc_cohort7/patient_data/primary_diagnosis/primary_diagnosis|code": "44803809",
    "crc_cohort7/patient_data/primary_diagnosis/primary_diagnosis|terminology": "omop_vocabulary",
    "crc_cohort7/patient_data/primary_diagnosis/encoding|code": "UTF-8",
    "crc_cohort7/patient_data/primary_diagnosis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/patient_data/primary_diagnosis/language|code": "en",
    "crc_cohort7/patient_data/primary_diagnosis/language|terminology": "ISO_639-1"
}
    '''
    secondcomp='''
{
    "crc_cohort7/_uid": "0c770609-2ded-4c0f-aa7b-9b9352f6c90c::local.ehrbase.org::1",
    "crc_cohort7/category|code": "433",
    "crc_cohort7/category|terminology": "openehr",
    "crc_cohort7/category|value": "event",
    "crc_cohort7/composer|name": "EOSC-Life_WP1-DEM",
    "crc_cohort7/context/case_identification/participation_in_clinical_study": "FALSE",
    "crc_cohort7/context/case_identification/patient_pseudonym": "59499",
    "crc_cohort7/context/setting|code": "238",
    "crc_cohort7/context/setting|terminology": "openehr",
    "crc_cohort7/context/setting|value": "other care",
    "crc_cohort7/context/start_time": "2022-03-15T12:04:38.49Z",
    "crc_cohort7/diagnostic_examinations/colonoscopy/colonoscopy": "Not done",
    "crc_cohort7/diagnostic_examinations/colonoscopy/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/colonoscopy/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/colonoscopy/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/colonoscopy/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/colonoscopy/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/colonoscopy/language|code": "en",
    "crc_cohort7/diagnostic_examinations/colonoscopy/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/colonoscopy/procedure_name": "Colonoscopy",
    "crc_cohort7/diagnostic_examinations/colonoscopy/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/diagnostic_examinations/ct/ct": "Done, data available",
    "crc_cohort7/diagnostic_examinations/ct/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/ct/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/ct/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/ct/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/ct/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/ct/language|code": "en",
    "crc_cohort7/diagnostic_examinations/ct/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/ct/procedure_name": "CT",
    "crc_cohort7/diagnostic_examinations/ct/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/diagnostic_examinations/liver_imaging/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/liver_imaging/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/liver_imaging/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/liver_imaging/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/liver_imaging/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/liver_imaging/language|code": "en",
    "crc_cohort7/diagnostic_examinations/liver_imaging/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/liver_imaging/liver_imaging": "Done, data available",
    "crc_cohort7/diagnostic_examinations/liver_imaging/procedure_name": "Liver imaging",
    "crc_cohort7/diagnostic_examinations/liver_imaging/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/diagnostic_examinations/lung_imaging/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/lung_imaging/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/lung_imaging/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/lung_imaging/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/lung_imaging/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/lung_imaging/language|code": "en",
    "crc_cohort7/diagnostic_examinations/lung_imaging/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/lung_imaging/lung_imaging": "Done, data available",
    "crc_cohort7/diagnostic_examinations/lung_imaging/procedure_name": "Lung imaging",
    "crc_cohort7/diagnostic_examinations/lung_imaging/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/diagnostic_examinations/mri/encoding|code": "UTF-8",
    "crc_cohort7/diagnostic_examinations/mri/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/diagnostic_examinations/mri/ism_transition/current_state|code": "532",
    "crc_cohort7/diagnostic_examinations/mri/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/diagnostic_examinations/mri/ism_transition/current_state|value": "completed",
    "crc_cohort7/diagnostic_examinations/mri/language|code": "en",
    "crc_cohort7/diagnostic_examinations/mri/language|terminology": "ISO_639-1",
    "crc_cohort7/diagnostic_examinations/mri/mri": "Unknown",
    "crc_cohort7/diagnostic_examinations/mri/procedure_name": "MRI",
    "crc_cohort7/diagnostic_examinations/mri/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/encoding|code": "UTF-8",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/language|code": "en",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/language|terminology": "ISO_639-1",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/localization_of_primary_tumor|code": "74582",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/localization_of_primary_tumor|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/localization_of_primary_tumor|value": "C 20 - Rectum",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/problem_diagnosis_name|code": "44803809",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/problem_diagnosis_name|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/problem_diagnosis_name|value": "Colorectal cancer",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/distant_metastasis/anatomical_location:0/localization_of_metastasis|code": "45881859",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/distant_metastasis/anatomical_location:0/localization_of_metastasis|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/distant_metastasis/anatomical_location:0/localization_of_metastasis|value": "Lymph Nodes",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/histological_grading/who_version": "2nd ed. (1991- 2000)",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/morphology|code": "42530737",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/morphology|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/morphology|value": "Adenocarcinoma",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/distant_metastasis|code": "45876323",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/distant_metastasis|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/distant_metastasis|value": "MX",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/grade|code": "36769033",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/grade|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/grade|value": "G3",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/primary_tumour|code": "4234703",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/primary_tumour|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/primary_tumour|value": "T3",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/regional_lymph_nodes|code": "45881614",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/regional_lymph_nodes|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/regional_lymph_nodes|value": "N2",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/stage|code": "45878643",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/stage|terminology": "omop_vocabulary",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/stage|value": "Stage - III",
    "crc_cohort7/histopathology/result_group/cancer_diagnosis/synoptic_details_-_colorectal_cancer/microscopic_findings/tnm_pathological_classification/uicc_version": "5th. ed (used 1998-2002)",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/anatomical_pathology_examination/anatomical_pathology_finding:0/media_file/availability_digital_imaging": "Can be generated",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/invasion_front/anatomical_pathology_finding/digital_imaging_invasion_front/availability_invasion_front_digital_imaging": "Can be generated",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/test_name": "Histopathology analysis",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/any_event:0/time": "2018-11-07T00:00:00Z",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/encoding|code": "UTF-8",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/language|code": "en",
    "crc_cohort7/histopathology/result_group/laboratory_test_result/language|terminology": "ISO_639-1",
    "crc_cohort7/language|code": "en",
    "crc_cohort7/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/kras_exon_2_codons_12_or_13|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/kras_exon_2_codons_12_or_13|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/kras_exon_2_codons_12_or_13|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_2_codons_12_or_13/variant_name": "KRAS exon 2 (codons 12 or 13)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/kras_exon_3_codons_59_or_61|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/kras_exon_3_codons_59_or_61|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/kras_exon_3_codons_59_or_61|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_3_codons_59_or_61/variant_name": "KRAS exon 3 (codons 59 or 61)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/kras_exon_4_codons_117_or_146|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/kras_exon_4_codons_117_or_146|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/kras_exon_4_codons_117_or_146|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/kras_exon_4_codons_117_or_146/variant_name": "KRAS exon 4 (codons 117 or 146)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/nras_exon_2_codons_12_or_13|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/nras_exon_2_codons_12_or_13|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/nras_exon_2_codons_12_or_13|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_2_codons_12_or_13/variant_name": "NRAS exon 2 (codons 12 or 13)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/nras_exon_3_codons_59_or_61|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/nras_exon_3_codons_59_or_61|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/nras_exon_3_codons_59_or_61|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_3_codons_59_or_61/variant_name": "NRAS exon 3 (codons 59 or 61)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/nras_exon_4_codons_117_or_146|code": "at0007",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/nras_exon_4_codons_117_or_146|terminology": "local",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/nras_exon_4_codons_117_or_146|value": "Indeterminate",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/nras_exon_4_codons_117_or_146/variant_name": "NRAS exon 4 (codons 117 or 146)",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/test_name": "KRAS mutation test",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/any_event:0/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/kras_mutation_status/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/any_event:0/microsatellite_instability": "Not done",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/any_event:0/test_name": "Microsatellite instability test",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/any_event:0/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/microsatellites_instability_analysis/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/any_event:0/mismatch_repair_gene_expression": "Not done",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/any_event:0/test_name": "Mismatch repair gene expression",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/any_event:0/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/mismatch_repair_gene_analysis/language|terminology": "ISO_639-1",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/any_event:0/braf_pic3ca_her2_mutation_status": "Not done",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/any_event:0/test_name": "BRAF, PIC3CA, HER2 mutation test",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/any_event:0/time": "9999-12-10T00:00:00Z",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/encoding|code": "UTF-8",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/language|code": "en",
    "crc_cohort7/molecular_markers/result_group/oncogenic_mutations_test/language|terminology": "ISO_639-1",
    "crc_cohort7/patient_data/gender/biological_sex|code": "8532",
    "crc_cohort7/patient_data/gender/biological_sex|terminology": "omop_vocabulary",
    "crc_cohort7/patient_data/gender/biological_sex|value": "FEMALE",
    "crc_cohort7/patient_data/gender/encoding|code": "UTF-8",
    "crc_cohort7/patient_data/gender/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/patient_data/gender/language|code": "en",
    "crc_cohort7/patient_data/gender/language|terminology": "ISO_639-1",
    "crc_cohort7/patient_data/metastasis_diagnosis/encoding|code": "UTF-8",
    "crc_cohort7/patient_data/metastasis_diagnosis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/patient_data/metastasis_diagnosis/language|code": "en",
    "crc_cohort7/patient_data/metastasis_diagnosis/language|terminology": "ISO_639-1",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis2/metastasis_diagnosis/from_event": "Primary diagnosis",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis2/metastasis_diagnosis/time_of_recurrence": "P784D",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis|code": "36769180",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis|terminology": "omop_vocabulary",
    "crc_cohort7/patient_data/metastasis_diagnosis/metastasis_diagnosis|value": "Metastasis",
    "crc_cohort7/patient_data/primary_diagnosis/date_of_diagnosis": "2000-03-01T00:00:00Z",
    "crc_cohort7/patient_data/primary_diagnosis/diagnosis_timing/primary_diagnosis:0/age_at_diagnosis": "P67Y",
    "crc_cohort7/patient_data/primary_diagnosis/encoding|code": "UTF-8",
    "crc_cohort7/patient_data/primary_diagnosis/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/patient_data/primary_diagnosis/language|code": "en",
    "crc_cohort7/patient_data/primary_diagnosis/language|terminology": "ISO_639-1",
    "crc_cohort7/patient_data/primary_diagnosis/primary_diagnosis|code": "44803809",
    "crc_cohort7/patient_data/primary_diagnosis/primary_diagnosis|terminology": "omop_vocabulary",
    "crc_cohort7/patient_data/primary_diagnosis/primary_diagnosis|value": "Colorectal cancer",
    "crc_cohort7/sample/biospecimen_summary:0/encoding|code": "UTF-8",
    "crc_cohort7/sample/biospecimen_summary:0/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/sample/biospecimen_summary:0/language|code": "en",
    "crc_cohort7/sample/biospecimen_summary:0/language|terminology": "ISO_639-1",
    "crc_cohort7/sample/biospecimen_summary:0/material_type|code": "4122248",
    "crc_cohort7/sample/biospecimen_summary:0/material_type|terminology": "omop_vocabulary",
    "crc_cohort7/sample/biospecimen_summary:0/material_type|value": "Tumor tissue sample",
    "crc_cohort7/sample/biospecimen_summary:0/preservation_mode|code": "37206850",
    "crc_cohort7/sample/biospecimen_summary:0/preservation_mode|terminology": "omop_vocabulary",
    "crc_cohort7/sample/biospecimen_summary:0/preservation_mode|value": "FFPE",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|assigner": "unknown",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|id": "557",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|issuer": "unknown",
    "crc_cohort7/sample/biospecimen_summary:0/sample_id|type": "unknown",
    "crc_cohort7/sample/biospecimen_summary:0/specimen/year_of_sample_collection": "2000-01-01T00:00:00Z",
    "crc_cohort7/surgery/surgery:0/encoding|code": "UTF-8",
    "crc_cohort7/surgery/surgery:0/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/surgery/surgery:0/ism_transition/current_state|code": "532",
    "crc_cohort7/surgery/surgery:0/ism_transition/current_state|terminology": "openehr",
    "crc_cohort7/surgery/surgery:0/ism_transition/current_state|value": "completed",
    "crc_cohort7/surgery/surgery:0/language|code": "en",
    "crc_cohort7/surgery/surgery:0/language|terminology": "ISO_639-1",
    "crc_cohort7/surgery/surgery:0/location_of_the_tumor|code": "74582",
    "crc_cohort7/surgery/surgery:0/location_of_the_tumor|terminology": "omop_vocabulary",
    "crc_cohort7/surgery/surgery:0/location_of_the_tumor|value": "C 20 - Rectum",
    "crc_cohort7/surgery/surgery:0/surgery_radicality|code": "4121182",
    "crc_cohort7/surgery/surgery:0/surgery_radicality|terminology": "omop_vocabulary",
    "crc_cohort7/surgery/surgery:0/surgery_radicality|value": "R0",
    "crc_cohort7/surgery/surgery:0/surgery_timing/surgery/from_event": "Primary diagnosis",
    "crc_cohort7/surgery/surgery:0/surgery_timing/surgery/surgery_start_relative": "P14D",
    "crc_cohort7/surgery/surgery:0/surgery_type|code": "4166855",
    "crc_cohort7/surgery/surgery:0/surgery_type|terminology": "omop_vocabulary",
    "crc_cohort7/surgery/surgery:0/surgery_type|value": "Anterior resection of rectum",
    "crc_cohort7/surgery/surgery:0/time": "2018-11-07T00:00:00Z",
    "crc_cohort7/territory|code": "ZW",
    "crc_cohort7/territory|terminology": "ISO_3166-1",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/encoding|code": "UTF-8",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/encoding|terminology": "IANA_character-sets",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/language|code": "en",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/language|terminology": "ISO_639-1",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status": "death for unknown reasons",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status_timing/overall_survival_status/from_event": "First colon cancer therapy",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status_timing/overall_survival_status/overall_survival_status": "P763D",
    "crc_cohort7/vital_status_and_survival_information/vital_status_and_survival_information/vital_status_timing/timestamp_of_last_update_of_vital_status": "2002-04-01"
}
'''
    origcomposition=json.loads(firstcomp)
    retrievedcomposition=json.loads(secondcomp)
    origchanged=myutils.change_naming(origcomposition)
    retrchanged=myutils.change_naming(retrievedcomposition)

    comparison_results=myutils.compare_jsons(origchanged,retrchanged)

    cr=json.loads(comparison_results)
    assert len(cr)==17

    ndiff=myutils.analyze_comparison_json(comparison_results)
    assert ndiff==0
